# Generated by Django 5.2.14 on 2026-05-07 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_dashboard', '0002_seed_loop_podcastone_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('new', 'New'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('processing', 'Processing'), ('review', 'Review'), ('processed', 'Processed'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('superseded', 'Superseded'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='ParsedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_path', models.CharField(max_length=1000, unique=True)),
                ('approved_path', models.CharField(blank=True, max_length=1000)),
                ('reporting_period', models.CharField(blank=True, max_length=80)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_impressions', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('comparison_status', models.CharField(db_index=True, default='pending', max_length=40)),
                ('comparison_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_outputs', to='pipeline_dashboard.asset')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_outputs', to='pipeline_dashboard.vendor')),
            ],
            options={
                'ordering': ['-created_at', 'vendor__name', 'output_path'],
                'indexes': [models.Index(fields=['vendor', 'comparison_status'], name='parsed_vendor_status_idx'), models.Index(fields=['asset', 'created_at'], name='parsed_asset_created_idx')],
            },
        ),
    ]
