# Generated by Django 5.2.14 on 2026-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_dashboard', '0006_rename_rallyadmedia_seed_adtaxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='duplicate_role',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('duplicate', 'Duplicate')], db_index=True, max_length=20),
        ),
    ]
