# Generated by Django 5.2.14 on 2026-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_dashboard', '0007_add_duplicate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
