from __future__ import annotations

from django.urls import path

from .views import (
    approve_parsed_output,
    approve_process_file,
    cancel_parsed_output,
    cancel_process_file,
    assign_vendor_folder,
    create_vendor,
    dashboard,
    delete_vendor,
    download_approved_output,
    download_approval_output,
    download_final_output,
    folders,
    parse_file_preview,
    parse_process_file,
    process,
    process_review_file,
    review_approval_file,
    review_final_file,
    review_file_preview,
    review_parsed_output,
    toggle_is_active,
    update_folders,
    update_process_vendor,
    update_vendor,
    vendor_details,
    vendor_reporting,
    vendors,
)


app_name = "pipeline_dashboard"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("process/", process, name="process"),
    path("process/<str:remote_item_id>/vendor/", update_process_vendor, name="update_process_vendor"),
    path("process/<str:remote_item_id>/cancel/", cancel_process_file, name="cancel_process_file"),
    path("process/<str:remote_item_id>/parse/preview/", parse_file_preview, name="parse_file_preview"),
    path("process/<str:remote_item_id>/parse/", parse_process_file, name="parse_process_file"),
    path("process/<str:remote_item_id>/approve/", approve_process_file, name="approve_process_file"),
    path("process/approval/<int:parsed_output_id>/approved/", approve_parsed_output, name="approve_parsed_output"),
    path("process/approval/<int:parsed_output_id>/cancel/", cancel_parsed_output, name="cancel_parsed_output"),
    path("process/approval/<int:parsed_output_id>/review/", review_parsed_output, name="review_parsed_output"),
    path("process/approval/<int:parsed_output_id>/download/", download_approved_output, name="download_approved_output"),
    path("folders/", folders, name="folders"),
    path("folders/update/", update_folders, name="update_folders"),
    path("folders/review/preview/", review_file_preview, name="review_file_preview"),
    path("folders/review/process/", process_review_file, name="process_review_file"),
    path("folders/toggle-active/", toggle_is_active, name="toggle_is_active"),
    path("folders/approval/<str:remote_item_id>/review/", review_approval_file, name="review_approval_file"),
    path("folders/approval/<str:remote_item_id>/download/", download_approval_output, name="download_approval_output"),
    path("folders/final/<str:remote_item_id>/review/", review_final_file, name="review_final_file"),
    path("folders/final/<str:remote_item_id>/download/", download_final_output, name="download_final_output"),
    path("vendors/", vendors, name="vendors"),
    path("vendors/<int:vendor_id>/details/", vendor_details, name="vendor_details"),
    path("vendors/<int:vendor_id>/reporting/", vendor_reporting, name="vendor_reporting"),
    path("vendors/create/", create_vendor, name="create_vendor"),
    path("vendors/<int:vendor_id>/update/", update_vendor, name="update_vendor"),
    path("vendors/<int:vendor_id>/delete/", delete_vendor, name="delete_vendor"),
    path("vendors/folders/<int:folder_id>/assign/", assign_vendor_folder, name="assign_vendor_folder"),
]
